spring:
  cloud:
    nacos:
      discovery:
        enabled: true
        server-addr: nacos3 #47.103.28.119:8848 # 在dev prod中配置
      config:
        enabled: true
        server-addr: nacos3 # 47.103.28.119:8848 # 在dev prod中配置
        file-extension: yml  # 必须修改成yaml或者yml
        group: DEFAULT_GROUP  # 缺省即可
        prefix: ${spring.application.name} # 缺省即可