server:
  port: 8002
  servlet:
    context-path: /service
spring:
  application:
    name: weiji-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://47.103.28.119:3306/weiji_env?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    url: jdbc:mysql://mysql-java:3306/weiji_env?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: Yifan123.
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
#Mybatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.fujiang.weiji
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*.xml
